# -*- coding: utf-8 -*-
"""sentimenet1.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_D2mAKJU0HTllqV23MLNbEBJtr8L4lv
"""

!jupyter nbconvert --to script your_notebook.ipynb

import pandas as pd
import zipfile
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("/content/Womens Clothing E-Commerce Reviews.csv.zip")

print("Initial shape:", df.shape)
print(df.columns)

df = df[['Review Text', 'Rating']].dropna()
df = df[df['Rating'] != 3]

df['Sentiment'] = df['Rating'].apply(lambda x: 'positive' if x >= 4 else 'negative')

vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['Review Text'])

le = LabelEncoder()
y = le.fit_transform(df['Sentiment'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, target_names=le.classes_))